sudo: required

services:
    - docker

language: cpp

git:
    submodules: false

before_install:
    - docker run --rm --name asgard -d -v $(pwd):/src navitia/asgard-dev:latest sh -c 'while true; do sleep 10; done'
    - sed -i 's,git\@github.com:\([^/]*\)/\(.*\).git,https://github.com/\1/\2,' .gitmodules
    - git submodule update --init
script:
    - docker exec asgard sh -c 'mkdir build && cd build && cmake /src && make && cd asgard && ctest'
    - docker kill asgard
